"""Markdown output formatting for analysis results."""

import logging
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from scatter.analyzers.coupling_analyzer import CycleGroup, ProjectMetrics
from scatter.analyzers.health_analyzer import HealthDashboard
from scatter.core.graph import DependencyGraph
from scatter.core.models import FilterPipeline, ImpactReport
from scatter.reports.console_reporter import render_tree
from scatter.reports.graph_reporter import generate_mermaid


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _escape_cell(value: str) -> str:
    """Sanitize a value for use inside a markdown table cell."""
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _fmt_metadata(metadata: Optional[Dict]) -> str:
    """Return an italic footer line with version and timestamp."""
    if metadata is None:
        return ""
    version = metadata.get("scatter_version", "unknown")
    timestamp = metadata.get("timestamp", "unknown")
    return f"\n*Generated by Scatter v{version} at {timestamp}*\n"


def _fmt_pipeline(pipeline: Optional[FilterPipeline]) -> str:
    """Return a markdown blockquote with search scope and filter chain."""
    if pipeline is None:
        return ""
    projects = f"{pipeline.total_projects_scanned:,}"
    files = f"{pipeline.total_files_scanned:,}"
    lines = [
        f"> **Search scope:** {pipeline.search_scope} (scanned {projects} projects, {files} files)"
    ]
    if pipeline.stages:
        lines.append(f"> **Filter:** {pipeline.format_arrow_chain()}")
    return "\n".join(lines) + "\n"


def _write_file(content: str, output_file_path: Path) -> None:
    """Write UTF-8 content to file, creating parent dirs as needed."""
    try:
        output_file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file_path, "w", encoding="utf-8") as f:
            f.write(content)
        logging.info(f"Successfully wrote markdown report to: {output_file_path}")
    except Exception as e:
        logging.error(f"Failed to write markdown report: {e}")


def _md_table(headers: List[str], rows: List[List[str]]) -> str:
    """Build a markdown table from headers and rows. All values escaped."""
    header_line = "| " + " | ".join(_escape_cell(h) for h in headers) + " |"
    separator = "| " + " | ".join("---" for _ in headers) + " |"
    lines = [header_line, separator]
    for row in rows:
        padded = list(row) + [""] * (len(headers) - len(row))
        lines.append("| " + " | ".join(_escape_cell(str(v)) for v in padded) + " |")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Legacy mode (git / target / sproc)
# ---------------------------------------------------------------------------


def build_markdown(
    detailed_results: List[Dict[str, Any]],
    metadata: Optional[Dict] = None,
    pipeline: Optional[FilterPipeline] = None,
    graph_metrics_requested: bool = False,
) -> str:
    """Build markdown string for legacy consumer analysis results."""
    parts: List[str] = ["# Consumer Analysis Report\n"]

    pipeline_block = _fmt_pipeline(pipeline)
    if pipeline_block:
        parts.append(pipeline_block)

    if not detailed_results:
        parts.append("No consuming relationships found.\n")
    else:
        # Group by (TargetProjectName, TriggeringType) — same as console reporter
        group_counts = Counter(
            (item["TargetProjectName"], item["TriggeringType"]) for item in detailed_results
        )
        last_target_type = None
        current_rows: List[List[str]] = []

        headers = ["Consumer", "Path", "Pipeline", "Solutions"]
        if graph_metrics_requested:
            headers.extend(["Coupling", "Fan-In", "Fan-Out", "Instability", "In Cycle"])

        def _flush_table() -> None:
            if current_rows:
                parts.append(_md_table(headers, current_rows))
                parts.append("")
                current_rows.clear()

        for item in detailed_results:
            current_target_type = (item["TargetProjectName"], item["TriggeringType"])
            if current_target_type != last_target_type:
                _flush_table()
                count = group_counts[current_target_type]
                parts.append(
                    f"## {item['TargetProjectName']} ({item['TargetProjectPath']}) ({count} consumer(s))\n"
                )
                if "N/A" not in item["TriggeringType"]:
                    parts.append(f"Type/Level: {item['TriggeringType']}\n")
                last_target_type = current_target_type

            pipeline_name = item.get("PipelineName") or "\u2014"
            solutions = item.get("ConsumingSolutions", [])
            solutions_str = ", ".join(solutions) if solutions else "\u2014"
            row: List[str] = [
                item["ConsumerProjectName"],
                item["ConsumerProjectPath"],
                pipeline_name,
                solutions_str,
            ]
            if graph_metrics_requested:
                cs = item.get("CouplingScore")
                row.extend(
                    [
                        str(cs) if cs is not None else "\u2014",
                        str(item.get("FanIn", "\u2014")),
                        str(item.get("FanOut", "\u2014")),
                        f"{item['Instability']:.3f}"
                        if item.get("Instability") is not None
                        else "\u2014",
                        "yes"
                        if item.get("InCycle")
                        else "no"
                        if item.get("InCycle") is not None
                        else "\u2014",
                    ]
                )
            current_rows.append(row)

        _flush_table()

        target_names = {item["TargetProjectName"] for item in detailed_results}
        parts.append(
            f"---\n**Total:** {len(detailed_results)} consuming relationship(s) across {len(target_names)} target(s).\n"
        )

    meta = _fmt_metadata(metadata)
    if meta:
        if not any(p.startswith("---") for p in parts[-2:]):
            parts.append("---")
        parts.append(meta.lstrip())

    return "\n".join(parts)


def write_markdown_report(
    detailed_results: List[Dict[str, Any]],
    output_file_path: Path,
    metadata: Optional[Dict] = None,
    pipeline: Optional[FilterPipeline] = None,
    graph_metrics_requested: bool = False,
) -> None:
    """Write legacy consumer analysis results as markdown to file."""
    content = build_markdown(
        detailed_results,
        metadata=metadata,
        pipeline=pipeline,
        graph_metrics_requested=graph_metrics_requested,
    )
    _write_file(content, output_file_path)


# ---------------------------------------------------------------------------
# Impact mode
# ---------------------------------------------------------------------------


def build_impact_markdown(
    report: ImpactReport,
    metadata: Optional[Dict] = None,
    graph_metrics_requested: bool = False,
) -> str:
    """Build markdown string for impact analysis report."""
    parts: List[str] = ["# Impact Analysis\n"]

    # Work request
    sow_display = report.sow_text[:200] + "..." if len(report.sow_text) > 200 else report.sow_text
    parts.append(f"**Work Request:** {sow_display}\n")

    # Risk / complexity summary
    risk_str = report.overall_risk or "Not assessed"
    complexity_str = report.complexity_rating or "Not assessed"
    effort_str = f" ({report.effort_estimate})" if report.effort_estimate else ""
    parts.append(f"**Overall Risk:** {risk_str} | **Complexity:** {complexity_str}{effort_str}\n")

    if not report.targets:
        parts.append("No analysis targets were identified.\n")
    else:
        for ti in report.targets:
            parts.append(f"## {ti.target.name}\n")
            parts.append(
                f"Direct Consumers: {ti.total_direct} | Transitive: {ti.total_transitive}\n"
            )

            if ti.consumers:
                # Blast radius tree in code block
                tree_lines = render_tree(ti.consumers)
                if tree_lines:
                    parts.append("### Blast Radius\n")
                    parts.append("```text")
                    parts.extend(tree_lines)
                    parts.append("```\n")

                # Flat consumer detail table
                parts.append("### Consumer Detail\n")
                detail_headers = [
                    "Consumer",
                    "Confidence",
                    "Depth",
                    "Via",
                    "Risk",
                    "Pipeline",
                    "Solutions",
                ]
                if graph_metrics_requested:
                    detail_headers.extend(
                        ["Coupling", "Fan-In", "Fan-Out", "Instability", "In Cycle"]
                    )
                rows: List[List[str]] = []
                for c in ti.consumers:
                    depth_display = "direct" if c.depth == 0 else str(c.depth)
                    via = c.propagation_parent or "\u2014"
                    risk = c.risk_rating or "\u2014"
                    pipeline_name = c.pipeline_name or "\u2014"
                    solutions = ", ".join(c.solutions) if c.solutions else "\u2014"
                    row = [
                        c.consumer_name,
                        c.confidence_label,
                        depth_display,
                        via,
                        risk,
                        pipeline_name,
                        solutions,
                    ]
                    if graph_metrics_requested:
                        row.extend(
                            [
                                str(c.coupling_score) if c.coupling_score is not None else "\u2014",
                                str(c.fan_in) if c.fan_in is not None else "\u2014",
                                str(c.fan_out) if c.fan_out is not None else "\u2014",
                                f"{c.instability:.3f}" if c.instability is not None else "\u2014",
                                "yes"
                                if c.in_cycle
                                else "no"
                                if c.in_cycle is not None
                                else "\u2014",
                            ]
                        )
                    rows.append(row)
                parts.append(_md_table(detail_headers, rows))
                parts.append("")

    # Complexity justification
    if report.complexity_justification:
        parts.append("### Complexity\n")
        parts.append(f"{report.complexity_rating}: {report.complexity_justification}\n")

    # Impact narrative
    if report.impact_narrative:
        parts.append("### Impact Summary\n")
        parts.append(f"{report.impact_narrative}\n")

    meta = _fmt_metadata(metadata)
    if meta:
        parts.append(f"---\n{meta.lstrip()}")

    return "\n".join(parts)


def write_impact_markdown_report(
    report: ImpactReport,
    output_file_path: Path,
    metadata: Optional[Dict] = None,
    graph_metrics_requested: bool = False,
) -> None:
    """Write impact analysis report as markdown to file."""
    content = build_impact_markdown(
        report, metadata=metadata, graph_metrics_requested=graph_metrics_requested
    )
    _write_file(content, output_file_path)


# ---------------------------------------------------------------------------
# Graph mode
# ---------------------------------------------------------------------------


def build_graph_markdown(
    graph: DependencyGraph,
    metrics: Dict[str, ProjectMetrics],
    ranked: List[Tuple[str, ProjectMetrics]],
    cycles: List[CycleGroup],
    clusters: Optional[List] = None,
    metadata: Optional[Dict] = None,
    dashboard: Optional[HealthDashboard] = None,
) -> str:
    """Build markdown string for dependency graph analysis report."""
    parts: List[str] = ["# Dependency Graph Analysis\n"]

    # Summary stats table
    parts.append(
        _md_table(
            ["Metric", "Value"],
            [
                ["Projects", str(graph.node_count)],
                ["Dependencies", str(graph.edge_count)],
                ["Connected components", str(len(graph.connected_components))],
                ["Circular dependencies", str(len(cycles))],
            ],
        )
    )
    parts.append("")

    # Top coupled projects
    if ranked:
        parts.append("## Top Coupled Projects\n")
        rows: List[List[str]] = []
        for name, m in ranked:
            rows.append(
                [
                    name,
                    f"{m.coupling_score:.1f}",
                    str(m.fan_in),
                    str(m.fan_out),
                    f"{m.instability:.2f}",
                ]
            )
        parts.append(
            _md_table(
                ["Project", "Score", "Fan-In", "Fan-Out", "Instability"],
                rows,
            )
        )
        parts.append("")

    # Cycles
    if cycles:
        parts.append("## Circular Dependencies\n")
        for i, cg in enumerate(cycles, 1):
            cycle_str = " \u2192 ".join(cg.shortest_cycle + [cg.shortest_cycle[0]])
            parts.append(f"{i}. **[{cg.size} projects]** {cycle_str}")
        parts.append("")

    # Domain clusters
    if clusters:
        parts.append("## Domain Clusters\n")
        rows = []
        for clu in clusters:
            label = f"{clu.extraction_feasibility} ({clu.feasibility_score:.3f})"
            rows.append(
                [
                    clu.name,
                    str(len(clu.projects)),
                    f"{clu.cohesion:.3f}",
                    f"{clu.coupling_to_outside:.3f}",
                    label,
                ]
            )
        parts.append(
            _md_table(
                ["Cluster", "Size", "Cohesion", "Coupling", "Feasibility"],
                rows,
            )
        )
        parts.append("")

    # Observations
    if dashboard and dashboard.observations:
        parts.append("## Observations\n")
        for obs in dashboard.observations:
            parts.append(f"- **[{obs.severity}]** {obs.message}")
        parts.append("")

    # Mermaid dependency diagram
    mermaid = generate_mermaid(graph, clusters=clusters, top_n=20)
    if mermaid and mermaid.strip() != "graph TD":
        parts.append("## Dependency Diagram\n")
        parts.append("```mermaid")
        parts.append(mermaid.rstrip())
        parts.append("```\n")

    meta = _fmt_metadata(metadata)
    if meta:
        parts.append(f"---\n{meta.lstrip()}")

    return "\n".join(parts)


def write_graph_markdown_report(
    graph: DependencyGraph,
    metrics: Dict[str, ProjectMetrics],
    ranked: List[Tuple[str, ProjectMetrics]],
    cycles: List[CycleGroup],
    output_file_path: Path,
    clusters: Optional[List] = None,
    metadata: Optional[Dict] = None,
    dashboard: Optional[HealthDashboard] = None,
) -> None:
    """Write dependency graph analysis report as markdown to file."""
    content = build_graph_markdown(
        graph,
        metrics,
        ranked,
        cycles,
        clusters=clusters,
        metadata=metadata,
        dashboard=dashboard,
    )
    _write_file(content, output_file_path)
