"""Markdown output formatting for analysis results."""

import logging
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from scatter.analyzers.coupling_analyzer import CycleGroup, ProjectMetrics
from scatter.analyzers.health_analyzer import HealthDashboard
from scatter.core.graph import DependencyGraph
from scatter.core.models import FilterPipeline, ImpactReport
from scatter.reports.console_reporter import render_tree
from scatter.reports.graph_reporter import generate_mermaid


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _escape_cell(value: str) -> str:
    """Sanitize a value for use inside a markdown table cell."""
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _fmt_metadata(metadata: Optional[Dict]) -> str:
    """Return an italic footer line with version and timestamp."""
    if metadata is None:
        return ""
    version = metadata.get("scatter_version", "unknown")
    timestamp = metadata.get("timestamp", "unknown")
    return f"\n*Generated by Scatter v{version} at {timestamp}*\n"


def _fmt_pipeline(pipeline: Optional[FilterPipeline]) -> str:
    """Return a markdown blockquote with search scope and filter chain."""
    if pipeline is None:
        return ""
    projects = f"{pipeline.total_projects_scanned:,}"
    files = f"{pipeline.total_files_scanned:,}"
    lines = [
        f"> **Search scope:** {pipeline.search_scope} (scanned {projects} projects, {files} files)"
    ]
    if pipeline.stages:
        lines.append(f"> **Filter:** {pipeline.format_arrow_chain()}")
    return "\n".join(lines) + "\n"


def _write_file(content: str, output_file_path: Path) -> None:
    """Write UTF-8 content to file, creating parent dirs as needed."""
    try:
        output_file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file_path, "w", encoding="utf-8") as f:
            f.write(content)
        logging.info(f"Successfully wrote markdown report to: {output_file_path}")
    except Exception as e:
        logging.error(f"Failed to write markdown report: {e}")


def _md_table(headers: List[str], rows: List[List[str]]) -> str:
    """Build a markdown table from headers and rows. All values escaped."""
    header_line = "| " + " | ".join(_escape_cell(h) for h in headers) + " |"
    separator = "| " + " | ".join("---" for _ in headers) + " |"
    lines = [header_line, separator]
    for row in rows:
        padded = list(row) + [""] * (len(headers) - len(row))
        lines.append("| " + " | ".join(_escape_cell(str(v)) for v in padded) + " |")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Risk highlights & column legend (for PR comments)
# ---------------------------------------------------------------------------


def _build_risk_highlights(results: List[Dict[str, Any]]) -> str:
    """Identify highest-risk consumers and return a readable summary."""
    # Only consider rows with graph metrics populated
    enriched = [
        r for r in results if r.get("FanIn") is not None and r.get("Instability") is not None
    ]
    if not enriched:
        return ""

    # Find consumers worth calling out:
    # 1. Stable + high fan-in = most dangerous (change ripples widely)
    # 2. In a dependency cycle = entangled, harder to isolate
    stable_and_popular = sorted(
        [r for r in enriched if r["Instability"] <= 0.5 and r["FanIn"] >= 5],
        key=lambda r: r["FanIn"],
        reverse=True,
    )
    most_coupled = sorted(enriched, key=lambda r: r.get("CouplingScore", 0) or 0, reverse=True)
    lowest_risk = sorted(
        [r for r in enriched if r["Instability"] >= 0.7 and not r.get("InCycle")],
        key=lambda r: r["FanIn"],
    )

    lines: List[str] = ["### Risk Highlights\n"]
    has_content = False

    if stable_and_popular:
        top = stable_and_popular[:3]
        names = ", ".join(f"**{r['ConsumerProjectName']}**" for r in top)
        lines.append(
            f"Highest risk: {names} "
            f"— stable (low instability) with high fan-in. "
            f"Many other projects depend on these, so breakage here cascades.\n"
        )
        has_content = True

    if most_coupled and most_coupled[0].get("CouplingScore", 0):
        top_coupled = most_coupled[0]
        score = top_coupled["CouplingScore"]
        if score and score > 500:
            lines.append(
                f"Most coupled: **{top_coupled['ConsumerProjectName']}** (score {score:.0f}). "
                f"This project has the densest web of dependencies in the result set.\n"
            )
            has_content = True

    if lowest_risk:
        if len(lowest_risk) <= 3:
            names = ", ".join(f"**{r['ConsumerProjectName']}**" for r in lowest_risk)
        else:
            names = f"{len(lowest_risk)} consumers"
        lines.append(
            f"Lowest risk: {names} "
            f"— unstable (high instability) and not in a cycle. "
            f"These are leaf-like projects, safe to change.\n"
        )
        has_content = True

    cycle_count = sum(1 for r in enriched if r.get("InCycle"))
    if cycle_count > 0:
        lines.append(
            f"{cycle_count} of {len(enriched)} consumer(s) are in a dependency cycle. "
            f"Changes may propagate in unexpected directions within cycles.\n"
        )
        has_content = True

    if not has_content:
        return ""

    return "\n".join(lines)


def _column_legend() -> str:
    """Return a collapsible legend explaining the graph enrichment columns."""
    return (
        "<details>\n"
        "<summary>What do these columns mean?</summary>\n\n"
        "| Column | Meaning |\n"
        "| --- | --- |\n"
        "| **Coupling** | Weighted sum of all dependency edges touching this project. "
        "Higher = more interconnected. |\n"
        "| **Fan-In** | How many projects depend on this one (via project reference). "
        "High fan-in = widely used. |\n"
        "| **Fan-Out** | How many projects this one depends on. "
        "High fan-out = lots of dependencies. |\n"
        "| **Instability** | `fan-out / (fan-in + fan-out)`. "
        "0.0 = stable (many dependents, change carefully). "
        "1.0 = unstable (leaf node, easy to change). |\n"
        "| **In Cycle** | Part of a circular dependency chain. "
        "Changes in cycles can propagate in unexpected directions. |\n"
        "\n</details>\n"
    )


# ---------------------------------------------------------------------------
# Legacy mode (git / target / sproc)
# ---------------------------------------------------------------------------


def build_markdown(
    detailed_results: List[Dict[str, Any]],
    metadata: Optional[Dict] = None,
    pipeline: Optional[FilterPipeline] = None,
    graph_metrics_requested: bool = False,
) -> str:
    """Build markdown string for legacy consumer analysis results."""
    parts: List[str] = ["# Consumer Analysis Report\n"]

    pipeline_block = _fmt_pipeline(pipeline)
    if pipeline_block:
        parts.append(pipeline_block)

    if not detailed_results:
        parts.append("No consuming relationships found.\n")
    else:
        # Group by (TargetProjectName, TriggeringType) — same as console reporter
        group_counts = Counter(
            (item["TargetProjectName"], item["TriggeringType"]) for item in detailed_results
        )
        last_target_type = None
        current_rows: List[List[str]] = []

        headers = ["Consumer", "Path", "Pipeline", "Solutions"]
        if graph_metrics_requested:
            headers.extend(["Coupling", "Fan-In", "Fan-Out", "Instability", "In Cycle"])

        def _flush_table() -> None:
            if current_rows:
                parts.append(_md_table(headers, current_rows))
                parts.append("")
                current_rows.clear()

        for item in detailed_results:
            current_target_type = (item["TargetProjectName"], item["TriggeringType"])
            if current_target_type != last_target_type:
                _flush_table()
                count = group_counts[current_target_type]
                parts.append(
                    f"## {item['TargetProjectName']} ({item['TargetProjectPath']}) ({count} consumer(s))\n"
                )
                if "N/A" not in item["TriggeringType"]:
                    parts.append(f"Type/Level: {item['TriggeringType']}\n")
                last_target_type = current_target_type

            pipeline_name = item.get("PipelineName") or "\u2014"
            solutions = item.get("ConsumingSolutions", [])
            solutions_str = ", ".join(solutions) if solutions else "\u2014"
            row: List[str] = [
                item["ConsumerProjectName"],
                item["ConsumerProjectPath"],
                pipeline_name,
                solutions_str,
            ]
            if graph_metrics_requested:
                cs = item.get("CouplingScore")
                row.extend(
                    [
                        str(cs) if cs is not None else "\u2014",
                        str(item.get("FanIn", "\u2014")),
                        str(item.get("FanOut", "\u2014")),
                        f"{item['Instability']:.3f}"
                        if item.get("Instability") is not None
                        else "\u2014",
                        "yes"
                        if item.get("InCycle")
                        else "no"
                        if item.get("InCycle") is not None
                        else "\u2014",
                    ]
                )
            current_rows.append(row)

        _flush_table()

        # Risk highlights and column legend (only when graph metrics present)
        if graph_metrics_requested and detailed_results:
            highlights = _build_risk_highlights(detailed_results)
            if highlights:
                parts.append(highlights)
            parts.append(_column_legend())

        target_names = {item["TargetProjectName"] for item in detailed_results}
        parts.append(
            f"---\n**Total:** {len(detailed_results)} consuming relationship(s) across {len(target_names)} target(s).\n"
        )

    meta = _fmt_metadata(metadata)
    if meta:
        if not any(p.startswith("---") for p in parts[-2:]):
            parts.append("---")
        parts.append(meta.lstrip())

    return "\n".join(parts)


def write_markdown_report(
    detailed_results: List[Dict[str, Any]],
    output_file_path: Path,
    metadata: Optional[Dict] = None,
    pipeline: Optional[FilterPipeline] = None,
    graph_metrics_requested: bool = False,
) -> None:
    """Write legacy consumer analysis results as markdown to file."""
    content = build_markdown(
        detailed_results,
        metadata=metadata,
        pipeline=pipeline,
        graph_metrics_requested=graph_metrics_requested,
    )
    _write_file(content, output_file_path)


# ---------------------------------------------------------------------------
# Impact mode
# ---------------------------------------------------------------------------


def build_impact_markdown(
    report: ImpactReport,
    metadata: Optional[Dict] = None,
    graph_metrics_requested: bool = False,
) -> str:
    """Build markdown string for impact analysis report."""
    parts: List[str] = ["# Impact Analysis\n"]

    # Work request
    sow_display = report.sow_text[:200] + "..." if len(report.sow_text) > 200 else report.sow_text
    parts.append(f"**Work Request:** {sow_display}\n")

    # --- Summary section ---
    parts.append("## Summary\n")

    # Narrative first (prose before numbers)
    if report.impact_narrative:
        parts.append(f"{report.impact_narrative}\n")

    # Stats table
    risk_str = report.overall_risk or "Not assessed"
    complexity_str = report.complexity_rating or "Not assessed"
    effort_str = f" ({report.effort_estimate})" if report.effort_estimate else ""

    total_direct = sum(ti.total_direct for ti in (report.targets or []))
    total_transitive = sum(ti.total_transitive for ti in (report.targets or []))

    # Collect unique pipeline names
    all_pipelines: List[str] = []
    for ti in report.targets or []:
        for c in ti.consumers:
            if c.pipeline_name:
                all_pipelines.append(c.pipeline_name)
    unique_pipelines = sorted(set(all_pipelines))
    pipelines_str = ", ".join(unique_pipelines) if unique_pipelines else "\u2014"

    # Identification confidence
    if report.ambiguity_level and report.avg_target_confidence is not None:
        confidence_str = (
            f"{report.ambiguity_level.capitalize()} "
            f"({len(report.targets or [])} target(s), avg {report.avg_target_confidence:.2f})"
        )
    else:
        confidence_str = "\u2014"

    stats_rows = [
        ["Risk", risk_str],
        ["Complexity", f"{complexity_str}{effort_str}"],
        ["Direct consumers", str(total_direct)],
        ["Transitive consumers", str(total_transitive)],
    ]
    if unique_pipelines:
        stats_rows.append(["Pipelines affected", pipelines_str])
    stats_rows.append(["Identification confidence", confidence_str])
    parts.append(_md_table(["Metric", "Value"], stats_rows))
    parts.append("")

    # --- Targets section ---
    if not report.targets:
        parts.append("No analysis targets were identified.\n")
    else:
        parts.append("## Targets\n")

        for ti in report.targets:
            parts.append(f"### {ti.target.name}\n")

            # Target confidence and evidence
            if ti.target.match_evidence:
                conf_label = (
                    "HIGH"
                    if ti.target.confidence >= 0.7
                    else "MEDIUM"
                    if ti.target.confidence >= 0.4
                    else "LOW"
                )
                parts.append(
                    f"**Confidence:** {ti.target.confidence:.2f} ({conf_label}) "
                    f"\u2014 {ti.target.match_evidence}\n"
                )

            parts.append(
                f"Direct Consumers: {ti.total_direct} | Transitive: {ti.total_transitive}\n"
            )

            if ti.consumers:
                # Blast radius tree in code block
                tree_lines = render_tree(ti.consumers)
                if tree_lines:
                    parts.append("#### Blast Radius\n")
                    parts.append("```text")
                    parts.extend(tree_lines)
                    parts.append("```\n")

                # Flat consumer detail table
                parts.append("#### Affected Projects\n")
                has_pipelines = any(c.pipeline_name for c in ti.consumers)
                has_solutions = any(c.solutions for c in ti.consumers)
                detail_headers = [
                    "Consumer",
                    "Confidence",
                    "Depth",
                    "Via",
                    "Risk",
                ]
                if has_pipelines:
                    detail_headers.append("Pipeline")
                if has_solutions:
                    detail_headers.append("Solutions")
                if graph_metrics_requested:
                    detail_headers.extend(
                        ["Coupling", "Fan-In", "Fan-Out", "Instability", "In Cycle"]
                    )
                rows: List[List[str]] = []
                for c in ti.consumers:
                    depth_display = "direct" if c.depth == 0 else str(c.depth)
                    via = c.propagation_parent or "\u2014"
                    risk = c.risk_rating or "\u2014"
                    row = [
                        c.consumer_name,
                        c.confidence_label,
                        depth_display,
                        via,
                        risk,
                    ]
                    if has_pipelines:
                        row.append(c.pipeline_name or "\u2014")
                    if has_solutions:
                        row.append(", ".join(c.solutions) if c.solutions else "\u2014")
                    if graph_metrics_requested:
                        row.extend(
                            [
                                str(c.coupling_score) if c.coupling_score is not None else "\u2014",
                                str(c.fan_in) if c.fan_in is not None else "\u2014",
                                str(c.fan_out) if c.fan_out is not None else "\u2014",
                                f"{c.instability:.3f}" if c.instability is not None else "\u2014",
                                "yes"
                                if c.in_cycle
                                else "no"
                                if c.in_cycle is not None
                                else "\u2014",
                            ]
                        )
                    rows.append(row)
                parts.append(_md_table(detail_headers, rows))
                parts.append("")

    # Complexity justification
    if report.complexity_justification:
        parts.append("### Complexity\n")
        parts.append(f"{report.complexity_rating}: {report.complexity_justification}\n")

    # --- Next Steps section ---
    next_steps = _build_next_steps(report, total_direct, total_transitive, unique_pipelines)
    if next_steps:
        parts.append("## Next Steps\n")
        for step in next_steps:
            parts.append(f"- {step}")
        parts.append("")

    meta = _fmt_metadata(metadata)
    if meta:
        parts.append(f"---\n{meta.lstrip()}")

    return "\n".join(parts)


def _build_next_steps(
    report: ImpactReport,
    total_direct: int,
    total_transitive: int,
    unique_pipelines: List[str],
) -> List[str]:
    """Build template-driven next steps based on report data."""
    steps: List[str] = []

    if total_direct > 0:
        steps.append(
            f"Review the **{total_direct} direct consumer(s)** listed above for breaking changes"
        )

    if unique_pipelines:
        steps.append(
            f"Coordinate deployment with pipeline owners for: {', '.join(unique_pipelines)}"
        )

    risk = report.overall_risk
    if risk and risk in ("High", "Critical"):
        steps.append("Consider a design review before proceeding")
    elif risk and risk == "Medium":
        steps.append("Blast radius suggests staged rollout may reduce risk")

    if total_transitive > 0:
        steps.append("Verify transitive consumers (depth > 0) are not affected by contract changes")

    if report.ambiguity_level and report.ambiguity_level == "vague":
        steps.append(
            "Target identification has low confidence \u2014 verify targets before acting on this report"
        )

    return steps


def write_impact_markdown_report(
    report: ImpactReport,
    output_file_path: Path,
    metadata: Optional[Dict] = None,
    graph_metrics_requested: bool = False,
) -> None:
    """Write impact analysis report as markdown to file."""
    content = build_impact_markdown(
        report, metadata=metadata, graph_metrics_requested=graph_metrics_requested
    )
    _write_file(content, output_file_path)


# ---------------------------------------------------------------------------
# Graph mode
# ---------------------------------------------------------------------------


def build_graph_markdown(
    graph: DependencyGraph,
    metrics: Dict[str, ProjectMetrics],
    ranked: List[Tuple[str, ProjectMetrics]],
    cycles: List[CycleGroup],
    clusters: Optional[List] = None,
    metadata: Optional[Dict] = None,
    dashboard: Optional[HealthDashboard] = None,
) -> str:
    """Build markdown string for dependency graph analysis report."""
    parts: List[str] = ["# Dependency Graph Analysis\n"]

    # Summary stats table
    parts.append(
        _md_table(
            ["Metric", "Value"],
            [
                ["Projects", str(graph.node_count)],
                ["Dependencies", str(graph.edge_count)],
                ["Connected components", str(len(graph.connected_components))],
                ["Circular dependencies", str(len(cycles))],
            ],
        )
    )
    parts.append("")

    # Top coupled projects
    if ranked:
        parts.append("## Top Coupled Projects\n")
        rows: List[List[str]] = []
        for name, m in ranked:
            rows.append(
                [
                    name,
                    f"{m.coupling_score:.1f}",
                    str(m.fan_in),
                    str(m.fan_out),
                    f"{m.instability:.2f}",
                ]
            )
        parts.append(
            _md_table(
                ["Project", "Score", "Fan-In", "Fan-Out", "Instability"],
                rows,
            )
        )
        parts.append("")

    # Cycles
    if cycles:
        parts.append("## Circular Dependencies\n")
        for i, cg in enumerate(cycles, 1):
            cycle_str = " \u2192 ".join(cg.shortest_cycle + [cg.shortest_cycle[0]])
            parts.append(f"{i}. **[{cg.size} projects]** {cycle_str}")
        parts.append("")

    # Domain clusters
    if clusters:
        parts.append("## Domain Clusters\n")
        rows = []
        for clu in clusters:
            label = f"{clu.extraction_feasibility} ({clu.feasibility_score:.3f})"
            rows.append(
                [
                    clu.name,
                    str(len(clu.projects)),
                    f"{clu.cohesion:.3f}",
                    f"{clu.coupling_to_outside:.3f}",
                    label,
                ]
            )
        parts.append(
            _md_table(
                ["Cluster", "Size", "Cohesion", "Coupling", "Feasibility"],
                rows,
            )
        )
        parts.append("")

    # Observations
    if dashboard and dashboard.observations:
        parts.append("## Observations\n")
        for obs in dashboard.observations:
            parts.append(f"- **[{obs.severity}]** {obs.message}")
        parts.append("")

    # Mermaid dependency diagram
    mermaid = generate_mermaid(graph, clusters=clusters, top_n=20)
    if mermaid and mermaid.strip() != "graph TD":
        parts.append("## Dependency Diagram\n")
        parts.append("```mermaid")
        parts.append(mermaid.rstrip())
        parts.append("```\n")

    meta = _fmt_metadata(metadata)
    if meta:
        parts.append(f"---\n{meta.lstrip()}")

    return "\n".join(parts)


def write_graph_markdown_report(
    graph: DependencyGraph,
    metrics: Dict[str, ProjectMetrics],
    ranked: List[Tuple[str, ProjectMetrics]],
    cycles: List[CycleGroup],
    output_file_path: Path,
    clusters: Optional[List] = None,
    metadata: Optional[Dict] = None,
    dashboard: Optional[HealthDashboard] = None,
) -> None:
    """Write dependency graph analysis report as markdown to file."""
    content = build_graph_markdown(
        graph,
        metrics,
        ranked,
        cycles,
        clusters=clusters,
        metadata=metadata,
        dashboard=dashboard,
    )
    _write_file(content, output_file_path)
