using GalaxyWorks.Data.Models;

namespace GalaxyWorks.DevTools.Generators;

/// <summary>
/// Exports database schema documentation.
///
/// Note: This tool documents the PortalDataService stored procedure
/// mappings but does NOT call them. It reads .cs files and extracts
/// sproc names via regex for the schema catalog.
/// </summary>
public class SchemaExporter
{
    // Log messages that mention service names — not real usage
    private const string LogPrefix = "[SchemaExporter]";

    public void ExportSchema(string outputPath)
    {
        Console.WriteLine($"{LogPrefix} Scanning for stored procedures used by PortalDataService...");
        Console.WriteLine($"{LogPrefix} Found: sp_InsertPortalConfiguration");
        Console.WriteLine($"{LogPrefix} Found: sp_GetPortalConfigurationDetails");
        Console.WriteLine($"{LogPrefix} Writing schema for PortalDataService mappings to {outputPath}");

        // Real usage: we read the model to document its properties
        var props = typeof(PortalConfiguration).GetProperties();
        foreach (var prop in props)
        {
            Console.WriteLine($"{LogPrefix}   Column: {prop.Name} ({prop.PropertyType.Name})");
        }

        // String interpolation mentioning the service — NOT real usage
        var header = $"-- Schema export for tables used by PortalDataService\n" +
                     $"-- Generated by GalaxyWorks.DevTools.SchemaExporter\n" +
                     $"-- See PortalDataService.cs for the C# mapping\n";

        File.WriteAllText(outputPath, header);
    }
}
